### ISSUE TITLE
KeyError: 'service-data'

### ISSUE THREAD

**Issue by stevegardnersa** [Chapoly1305/FindMy#9] opened 2024-01-20 20:34 UTC
Firstly thank you for all the work on this project!

When running the web server and after entering my Apple ID, password and SMS 2FA code (first time only), I get the following error in the console

`File "/xxxxxxx/FindMy/web_service.py", line 49, in <module>
    'searchPartyToken': mobileme['delegates']['com.apple.mobileme']['service-data']['tokens'][
KeyError: 'service-data'`

Any advice on how to debug this?

**Comment by stevegardnersa** [comment] 2024-01-21 00:54
I did some further debugging and the value of **mobileme['delegates']['com.apple.mobileme']** is

`{'status': 1, 'status-message': 'Account limit reached.'}`

Any idea what's causing this? I created a fresh Apple ID for this

**Comment by apache21** [comment] 2024-01-23 13:28
You need to upgrade that iCloud account on proper Apple product to full support of keychain and icloud. (Ipad, Macbook, iphone)

**Comment by Chapoly1305** [comment] 2024-01-24 18:32
> You need to upgrade that iCloud account on proper Apple product to full support of keychain and icloud. (Ipad, Macbook, iphone)

It's good to know it worked for you @stevegardnersa 
I think @apache21  might be right about the cause. I had not experienced such issue and I don't recommend experimenting on your own iCloud account in case of getting banned or blocked and cause your personal data inaccessible.  I will add the project reminder, then close this ticket, since it's not directly caused by the project.

**Closed** 2024-02-01 15:55 UTC
